// Evitar falha nos testes por exceÃ§Ãµes nÃ£o tratadas
Cypress.on('uncaught:exception', (err, runnable) => {
    return false;
  });
  